### ISSUE TITLE
Modified Open Chisel

### ISSUE THREAD

**Issue by liuyangly25** [HKUST-Aerial-Robotics/open_quadtree_mapping#10]
Hello,

Thank you for your amazing work. I can run the demo bag without any issue. Now I want to try to create the global map. Can you share the modified open chisel?

Thanks,
Leon

**Comment by WANG-KX** [comment]
ok. I will try this weekend.

**Comment by liuyangly25** [comment]
@WANG-KX Thank you. I appreciate it.

**Comment by WANG-KX** [comment]
Here you are. https://github.com/WANG-KX/OpenChisel
I haven't used it recently, please read the code before usage.
