### ISSUE TITLE
When will the paper release? i have waited it so long :)

### ISSUE THREAD

**Issue by whu-lyh** [HKUST-Aerial-Robotics/open_quadtree_mapping#11]
Thx~

**Comment by WANG-KX** [comment]
Dear, 
Here I uploaded my manuscript of the paper.
[root_v0.pdf](https://github.com/HKUST-Aerial-Robotics/open_quadtree_mapping/files/2583496/root_v0.pdf)

**Comment by whu-lyh** [comment]
ok，Thx~
