### ISSUE TITLE
Message type

### ISSUE THREAD

**Issue by stevechan1993** [HKUST-Aerial-Robotics/open_quadtree_mapping#14]
I found the message from the topic "/vins_estimator/path" is quite the same as the datatype from the example bag except the frame id,so I modified the example.launch file to subscribe this topic,but still got the error of datatype which is:
[ INFO] [1546090057.543096310]: td 0.048238
[ERROR] [1546090057.621738910]: Client [/open_quadtree_mapping] wants topic /vins_estimator/camera_pose to have datatype/md5sum [geometry_msgs/PoseStamped/d3812c3cbc69362b77dc0b19b345f8f5], but our version has [nav_msgs/Odometry/cd5e73d190d741a2f92e81eda573aca7]. Dropping connection.
[ INFO] [1546090057.646040675]: td 0.048237

**Comment by WANG-KX** [comment]
Still, the message type is not correct. geometry_msgs/PoseStamped is not nav_msgs/Odometry.
Here is an example to convert.
[odom2pose.tar.gz](https://github.com/HKUST-Aerial-Robotics/open_quadtree_mapping/files/2717683/odom2pose.tar.gz)

**Comment by stevechan1993** [comment]
Thanks for answering,the pose message now is correct,so I use the realsense ZR300 camera to provide the image input which topic is "/camera/fisheye/image_raw",but got this OpenCV error:
 [ERROR] [1546240928.516905938]: cv_bridge exception: [8UC1] is not a color format. but [mono8] is. The conversion does not make sense
OpenCV Error: Assertion failed (ssize.area() > 0) in remapBilinear, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/imgwarp.cpp, line 662
OpenCV Error: Assertion failed (ssize.area() > 0) in remapBilinear, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/imgwarp.cpp, line 662
OpenCV Error: Assertion failed (ssize.area() > 0) in remapBilinear, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/imgwarp.cpp, line 662
OpenCV Error: Assertion failed (ssize.area() > 0) in remapBilinear, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/imgwarp.cpp, line 662
OpenCV Error: Assertion failed (ssize.area() > 0) in remapBilinear, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/imgwarp.cpp, line 662
OpenCV Error: Assertion failed (ssize.area() > 0) in remapBilinear, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/imgwarp.cpp, line 662
terminate called after throwing an instance of 'terminate called recursively
terminate called recursively
cv::Exception'

**Comment by WANG-KX** [comment]
Maybe you need more search in [google](http://lmgtfy.com/?q=cv_bridge+exception%3A+%5B8UC1%5D+is+not+a+color+format.+but+%5Bmono8%5D+is).
I guess the error is in type converting step.

**Comment by stevechan1993** [comment]
Thanks for your help.I have solved this problem.Now I find openchisel in your repository is missing some file.

**Comment by WANG-KX** [comment]
What kinds of files are missing?

**Comment by stevechan1993** [comment]
backward.hpp

**Comment by WANG-KX** [comment]
You can safely remove backward.hpp. Actually, it is not used :)
Remove line [21](https://github.com/WANG-KX/OpenChisel/blob/f263445204a092f88944688401d1efde78f72bbb/chisel_ros/src/ChiselNode.cpp#L21) to line 25.
