### ISSUE TITLE
CPU version

### ISSUE THREAD

**Issue by YiChenCityU** [HKUST-Aerial-Robotics/open_quadtree_mapping#15]
Dear Wang,

Thanks for your sharing. Do you have a CPU version of dense mapping of this work? Or do you know some works related to this. 
Thanks very much.

**Comment by WANG-KX** [comment]
Dear,

No, I do not have a version without CUDA acceleration. As far as I know, [FLAME](https://github.com/robustrobotics/flame) is the closest one to our work.

Kaixuan
