### ISSUE TITLE
So slow in Tx2 by using vins-fusion-gpu. But no problem by using example.bag 

### ISSUE THREAD

**Issue by pamzerbhu** [HKUST-Aerial-Robotics/open_quadtree_mapping#18]
Thanks for your read, When I using Vins-fusion-GPU to estimate position, so slow to come out these msgs(about 30s). Also, there is no pic in topic/open_quadtree/depth.
![Screenshot_2019-04-03_05-38-04](https://user-images.githubusercontent.com/22125165/55680430-1834a280-594c-11e9-8247-e20d258272ce.png)

**Comment by WANG-KX** [comment]
1, The image size is too big for TX2. Please try to resize it according to the paper.
2, The performance of the GPU on TX2 can be boosted, please check whether you are in low-power mode.
3, There is a filter to fuse temporal depth maps, and images are buffered first. It is normal to have nothing at the beginning. When the filter converges, you will get the result. I think the provided bag can demonstrate the effect.

**Comment by pamzerbhu** [comment]
YES, the bag performance is perfect，and I had set low size 320*240，start high-power mode as you can see in the picture. but still without depth image. Additional, I test it indoor. Is it has influence? My launch set as next pic:
![Screenshot_2019-04-03_06-21-06](https://user-images.githubusercontent.com/22125165/55681013-06ef9400-5954-11e9-9764-3eee8a69e8ee.png)
So I want to use my camera MYNT-EYE-D's depth for OpenChisel that you modified. but it reminds me  unrecognized depth image format. How shuld I modified? Next pic is my OpenChisel launch. Thanks for your help and reply.

![Screenshot_2019-04-03_06-17-21](https://user-images.githubusercontent.com/22125165/55681112-1c18f280-5955-11e9-88a1-802e18ff2c0b.png)

**Comment by WANG-KX** [comment]
1, Well, I can't see it is in high-performance mode from the picture. (Just make sure your self is ok).
2, The depth should be published in float32. I think my code publish this type of messages. If you are using other devices or codes, make sure the depth is in this format.
3, Indoor, outdoor does not make a difference for this method. Are you moving aggressively? Or the sequence is too short? You can check how I moved the camera in the bag or Youtube video.

**Comment by pamzerbhu** [comment]
My device SDK publish depth image format as mono16 ,colorimage format as rgb8. Now, I want to send these image into OpenChisel your modified directly. I should change the format first? In the kinect launch example, I found it support subscribed Kinect depth image directly. Can I send you a Wechat if it's convenient for you?

**Comment by WANG-KX** [comment]
Kinect? I checked my code and did not find Kinect launch. The modified open_chisel is only used for my depth map fusion. If you want to use other input, I am afraid you need to modify yourself. Please see https://github.com/WANG-KX/OpenChisel/blob/f263445204a092f88944688401d1efde78f72bbb/chisel_ros/include/chisel_ros/Conversions.h#L162

**Comment by WANG-KX** [comment]
My wechat tonybear_0728

**Comment by pamzerbhu** [comment]
Change Conversions.h line 168 to
 if(image->encoding == "16UC1" || image->encoding == "mono16") 
 solved the OpenChisel problem. Thanks a lot
