### ISSUE TITLE
the result is different when i run the same dataset twice

### ISSUE THREAD

**Issue by Wangxuefeng92** [HKUST-Aerial-Robotics/open_quadtree_mapping#23]
hi,
thanks for your project! i run your code, and the result is different when i run the same dataset twice.

**Comment by WANG-KX** [comment]
Do you mean depth maps are different?

**Comment by Wangxuefeng92** [comment]
yes, I input the same dataset. but the result is different

**Comment by WANG-KX** [comment]
Well, I never encountered it before. Does the dataset contain images and poses? As far as I know, there are no random functions.

**Comment by WANG-KX** [comment]
One possible reason is that the mapping cannot run in real-time on your machine such that some frames are dropped. This would cause inconsistent results.
