### ISSUE TITLE
Hello, what is the theoretical support for the depth_upsample.cu file?

### ISSUE THREAD

**Issue by yft1996** [HKUST-Aerial-Robotics/open_quadtree_mapping#25]
I didn't find the corresponding part in your paper.Can you explain it?

**Comment by WANG-KX** [comment]
Cite from the paper:

> The depth estimated by the dynamic belief propagation and high-gradient estimation covers the whole image and draw more attention to texture-rich regions. Interpolating estimations to get full dense results is a common method to solve optical flow [17]. Here, we extract full dense depth maps by minimizing a least-square cost.

**Comment by yft1996** [comment]
Thank you for your reply, this is very helpful to me.
