### ISSUE TITLE
CUDA Tesla

### ISSUE THREAD

**Issue by shermes91** [HKUST-Aerial-Robotics/open_quadtree_mapping#28]
Hi again,

I want to install Open Quadtree on a system with a NVidia 8400 GS. But catkin run an error for Compute capability version 11. 

It works until 30. Can I do something? Or is it not supported?

Best regards
Sebastian

**Comment by WANG-KX** [comment]
Sorry, I am not an expert on CUDA and do not even know 8400 GS:sweat:
Seems that the CC is 1.1 according to https://en.wikipedia.org/wiki/CUDA

**Comment by shermes91** [comment]
Yes, i have forgotten to close this issue. I need CUDA 6.5 but Ubuntu 16.04 supports version 8 and higher. But thanks!
