### ISSUE TITLE
How to save map like your video?

### ISSUE THREAD

**Issue by ltr-w** [HKUST-Aerial-Robotics/open_quadtree_mapping#31]
Hi ，I am not familiar with ROS , could you please tell me how to save map like your video , just like this 
![Quadtree-accelerated Real-time Monocular Dense Mapping mp4_20200813_145805705](https://user-images.githubusercontent.com/49608378/90104063-2d0e1b00-dd76-11ea-841b-bce9ba47b8b7.jpg)

**Comment by WANG-KX** [comment]
Hi, this is a recorded video from RVIZ.
