### ISSUE TITLE
example.bag download

### ISSUE THREAD

**Issue by niannianmeng** [HKUST-Aerial-Robotics/open_quadtree_mapping#6]
is the mainland China can access to the link for the example.bag?I tried, but failed

**Comment by WANG-KX** [comment]
Hello,
The .bag file is hosted at Dropbox and may be difficult for mainland China to access. I would like to host the file under the cloud you can access. Please tell me which cloud works best in mainland China? As far as I know, Baidu Yun may be too slow.

**Comment by WANG-KX** [comment]
Hello,
I have uploaded the file to OneDrive, please try this [link](https://1drv.ms/u/s!Av7Og_26nifdpwTQKNt6OhX5X2ed). Does it work well?

**Comment by niannianmeng** [comment]
Hi, KX,
thanks a lot for you reply, and try to upload another cloud OneDrive for me. but i still can not access to OneDrive link. as far as I know, Baidu yun is ok for me, is it too slow for you uplode file?

**Comment by WANG-KX** [comment]
Please try this [link](https://pan.baidu.com/s/17LcpYUflgBtoSaMskmWWDw)

**Comment by niannianmeng** [comment]
yes, it is ok, thank you very much
